[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn furniture_store.wsgi:application --bind 0.0.0.0:$PORT"

[deploy.environment]
DEBUG = "0"
DISABLE_COLLECTSTATIC = "0"
# Remove USE_AWS if you're not using S3 on Railway
# USE_AWS = "0"